# Generated by Django 3.0.9 on 2021-03-16 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=40)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
    ]
