# Generated by Django 3.0.9 on 2021-03-16 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_from', to='app.Customer')),
                ('to_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_to', to='app.Customer')),
            ],
        ),
    ]
