# Generated by Django 3.0.9 on 2021-03-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='from_field',
            new_name='trans_from',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_field',
            new_name='trans_to',
        ),
    ]
